### ISSUE TITLE
Does this implementation of AES have a backdoor?

### ISSUE THREAD

**Issue by EmmanuelMess** [7LPdWcaW/GrowTracker-Android#120]
The app states that:

> This is basic form of AES encryption based on a provided passphrase. This is not a guarantee form of encryption from law enforcement agencies as was designed to stop plain sight

How does AES not provide guarantee against anyone?

**Comment by 7LPdWcaW** [comment]
Its meant more of a disclaimer that although the contents are encrypted, its a basic form of encryption that could still probably be cracked relatively easy.

I dont think this encryption method has any backdoors, but obviously you cant really know because the manufacturer could have altered the java implementation for it.
