### ISSUE TITLE
New action : scrog

### ISSUE THREAD

**Issue by Maxtille** [7LPdWcaW/GrowTracker-Android#122]
It would be a good idea to implement scrog as an action.
If you don't know it's like an LST but on a horizontal grid, and it usually requires a few apex cut off :)

**Comment by Maxtille** [comment]
Oh and it means screen of green if I remember well

**Comment by 7LPdWcaW** [comment]
> And as an object scrog should contain one or several plants, which could be useful to reduce amount of manipulation needed to track watering, and leaf trimming for a scrog of 4 to 6 plants smile

I dont think this would necesserially work in the app at the current way its structured. I did have an idea to have the concept of "linked plants" but it didnt really work because you may as well just have 1 plant that tracks all (im currently doing this for my current grow) as if you needed to do anything for a single plant, you can reference it in the action notes (like topped: plant 1 of 5)

I think the knitting, tucking, or what ever would work as an action

**Comment by Maxtille** [comment]
I find the garden to be a good way to "link plants" especially when you grow different varieties in the same box. Notes is always a good solution but induce more redaction, and I like the idea to be able to track each plant individualy, even if I don't have the material to measure pH, EC, and run off. 
But what you say is very true :smile:

**Comment by Maxtille** [comment]
And as grid application will occur only once at each growing session, it can be set in notes. So for me it's all ok :smiley: :+1:
