### ISSUE TITLE
Add exit confirmation dialog when back pressed in water view

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#141]
When you press "Feed Again," the action is created at once, so if you then try to exit without pressing the green button in the lower right corner, the action will still be there.

**Comment by 7LPdWcaW** [comment]
This is actually intended behaviour, I see it more as a "you've applied the feeding again and now you are editing it" rather than a "copy from previous feeding" which is a separate option within the menu.

I chose this for instances where you may have pre-mixed nutrients that you use to water over multiple days (where the details do not change. basically a quick action for duplicate & set to current date)

**Comment by 9YbQiuEohUu1** [comment]
This is actually a good idea (I actually use it more often than creating a new watering to avoid typing the parameters each time). However, the fact that it saves the watering regardless of whether you confirm or cancel the action is counterintuitive and goes against the general behavior of android apps. E.g. I tap it by mistake, i press back and I expect it not to be there. Instead, I have to then go to history and delete it (worse yet, I may not go there at all and later find it and not even know whether it is a real watering or an erroneous duplicate). Again, not a big deal but rather a minor nuisance. Maybe a better idea would be "you've applied the feeding again and now you are editing it but if you press Back instead of Confirm you delete it."
Just to clarify - I realy like how functional the app is and how well the options are organized. Thank you for all the great work.

**Comment by 7LPdWcaW** [comment]
:+1: I think thats probably a reasonable addition
