### ISSUE TITLE
Adding Waterings and Notes from History tab?

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#227]
Currently, it is possible to add actions from History tab but not waterings or notes. This is somewthat counterintuitive since all three items can be viewed, edited, and deleted from there. Is it possible to make a floating button that would offer all three options? Here's an example from OmniNotes: a button expands into three "Add" options without eating up too much screen space. Can something similar be done here?
![88](https://user-images.githubusercontent.com/50482952/85521007-5202cf00-b60c-11ea-8dd2-3715c5a8d4fe.PNG)
![67777](https://user-images.githubusercontent.com/50482952/85521023-54fdbf80-b60c-11ea-95da-498f3f33188b.PNG)

**Comment by 7LPdWcaW** [comment]
This is unfortunately out of scope for the current version. Implementation of the FAB in the history is limited due to the way the actions are structured and changing it would require too much of my time that otherwise would be spent working on the future version.

I plan on doing something similar you can preview [here](https://www.reddit.com/r/GrowUtils/comments/hd4bs7/initial_designstructurenavigation/) for the future version
