### ISSUE TITLE
Need some clarification for translation

### ISSUE THREAD

**Issue by Maxtille** [7LPdWcaW/GrowTracker-Android#233]
I just thought we should clarify here (or maybe create a wiki ?) every different stages and special terms. It would be useful to be all at the same wavelength to provide a good translation. In addition a wiki would be useful as well for users. I think of it more as a complete explanation for technical terms than  a tutorial for growing
What do you think of it ?

**Comment by 7LPdWcaW** [comment]
Ill keep this in mind when sorting out translation strings for the future version, I believe there is a way for me to add context to strings and as the translation service was created after the fact, is lacking a lot of context. If there's any confusion or lack of understanding a term/phrase, I can clarify in #116. Most terms can be found on websites like www.growweedeasy.com although most of the terms are (should) be common in agriculture.

I want to steer away from creating any kind of wiki or knowledge base as the app/project is a utility one rather than an educational one and managing such a knowledge base will be a bad use of my time.
