### ISSUE TITLE
Restoring backup does not work for encrypted data

### ISSUE THREAD

**Issue by 9YbQiuEohUu1** [7LPdWcaW/GrowTracker-Android#79]
The app fails to restore backup when the data is encrypted. Only the unencrypted backup is restored successfully. Tested on two devices with different Android versions.

**Comment by 7LPdWcaW** [comment]
Are you able to provide any more info as to whats happening? If the app is set to encrypted mode and you backup/restore files backed up within encrypted mode, they should restore correctly. If the data was made _before_ encrypted mode was turned on, it will fail. Due to the way the files are backed up, I dont think would be possible to detect if the file is encrypted or just corrupted.

I will have to think more about this to make a fix.

**Comment by 9YbQiuEohUu1** [comment]
Here are all the details I have:
I have created several backups, one before turning the encryption on and two or three after. I then wiped the system and flased a new rom, I tried to restore the backup but only the first one (the unencrypted) was restored successfully. Other files just return an error message (unfortunately, I do not remember which one). 
It didn't occur to me that I could have tried to turn on encryption on the new device. 
Maybe it would be a good idea to add an error message that reads something like "Could not restore - data damaged or encrypted. Try turning the encryption on" or something like that.
Of course, it would be even better if the encrypted backup requested the password immediately upon restoring, if that is even possible. Omni Notes, for example, does exactly this.
